# vim:ft=kitty

foreground            #e2e2e3
background            #262626

selection_foreground  #e2e2e3
selection_background  #3b3e48

cursor                #e2e2e3
cursor_text_color     background

active_tab_background #2c2e34
active_tab_foreground #e2e2e3
active_tab_font_style bold
inactive_tab_background #2c2e34
inactive_tab_foreground #e2e2e3
inactive_tab_font_style normal

#black
color0                #181819
color8                #242426

#red
color1                #ff5f5f
color9                #ff5252

#green
color2                #87af5f
color10               #91bd66

#yellow
color3                #d7af5f
color11               #e3b964

#blue
color4                #87afd7
color12               #8fb9e3

#purple
color5                #d787d7
color13               #e38fe3

#orange
color6                #ffaf5f
color14               #ffaa54

#white
color7                #e2e2e3
color15               #f0f0f0
