
# Font
font_family      family="Iosevka Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

scrollback_lines 10000
scrollback_pager_history_size 100
scrollback_fill_enlarged_window yes

editor nvim

undercurl_style thick-sparse
url_style curly

cursor_trail 5
cursor_trail_decay 0.08  0.8
cursor_trail_start_threshold 2
cursor_shape block

window_margin_width 15
placement_strategy center
hide_window_decorations titlebar-only

background_blur 24
#background_opacity 0.90
dynamic_background_opacity yes

sync_to_monitor no
repaint_delay 8
input_delay 2

text_composition_strategy platform

strip_trailing_spaces smart

# load theme
include themes/kanagawa.conf
