
# Font
font_family      family="Iosevka Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0
scrollback_lines 10000

editor nvim

undercurl_style thick-sparse
url_style curly

cursor_trail 3
cursor_shape block

url_style curly

window_margin_width 15
placement_strategy center

# Vague theme
include themes/vague.conf
