
# Font
font_family      family="Iosevka Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0
disable_ligatures never

undercurl_style thick-sparse


url_style curly

cursor_trail 1
cursor_shape block
shell_integration enabled
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
mouse_hide_wait 3.0

url_style curly

window_padding_width 5
placement_strategy center

scrollback_lines 10000

# Mellow
include current-theme.conf
