background #0d0e0e
foreground #ebdbb2

cursor #ebdbb2
cursor_text_color #0d0e0e

selection_background #292929
selection_foreground #ebdbb2

color0 #060707
color1 #ea6962
color2 #a9b665
color3 #d8a657
color4 #7daea3
color5 #d3869b
color6 #89b482
color7 #d5c4a1

color8 #595959
color9 #f0837c
color10 #bfc985
color11 #e3ba7c
color12 #9dc3ba
color13 #ddaab9
color14 #a5c69f
color15 #ebdbb2
