foreground              #e8dcc2
background              #070707
selection_foreground    #070707
selection_background    #e8dcc2

cursor                  #e8dcc2
cursor_text_color       #070707

url_color               #8fb4a8

active_border_color     #8fb4a8
inactive_border_color   #353535

# Black
color0  #252525
color8  #6c6c6c
# Red
color1  #e46876
color9  #ff7f8c
# Green
color2  #98bb6c
color10 #b5d98c
# Yellow
color3  #e6c384
color11 #ffd58f
# Blue
color4  #7fb4ca
color12 #9ed0e3
# Magenta
color5  #c4a7e7
color13 #d8b8ff
# Cyan
color6  #7aa89f
color14 #9fd0c4
# White
color7  #dcd7ba
color15 #fff5d6

active_tab_foreground   #e8dcc2
active_tab_background   #141414
inactive_tab_foreground #6c6c6c
inactive_tab_background #070707
tab_bar_background      #070707
