return {
    {
        "catppuccin/nvim",
        name = "catppuccin",
        lazy = false,
        priority = 1000,
        config = function()
            require("catppuccin").setup({
                background = {
                    light = "latte",
                    dark = "mocha",
                },
                color_overrides = {
                    latte = {
                        rosewater = "#c14a4a",
                        flamingo = "#c14a4a",
                        red = "#c14a4a",
                        maroon = "#c14a4a",
                        pink = "#945e80",
                        mauve = "#945e80",
                        peach = "#c35e0a",
                        yellow = "#b47109",
                        green = "#6c782e",
                        teal = "#4c7a5d",
                        sky = "#4c7a5d",
                        sapphire = "#4c7a5d",
                        blue = "#45707a",
                        lavender = "#45707a",
                        text = "#654735",
                        subtext1 = "#73503c",
                        subtext0 = "#805942",
                        overlay2 = "#8c6249",
                        overlay1 = "#8c856d",
                        overlay0 = "#a69d81",
                        surface2 = "#bfb695",
                        surface1 = "#d1c7a3",
                        surface0 = "#e3dec3",
                        base = "#f9f5d7",
                        mantle = "#f0ebce",
                        crust = "#e8e3c8",
                    },
                    mocha = {
                        rosewater = "#ea6962",
                        flamingo = "#ea6962",
                        red = "#ea6962",
                        maroon = "#ea6962",
                        pink = "#d3869b",
                        mauve = "#d3869b",
                        peach = "#e78a4e",
                        yellow = "#d8a657",
                        green = "#a9b665",
                        teal = "#89b482",
                        sky = "#89b482",
                        sapphire = "#89b482",
                        blue = "#7daea3",
                        lavender = "#7daea3",
                        text = "#ebdbb2",
                        subtext1 = "#d5c4a1",
                        subtext0 = "#bdae93",
                        overlay2 = "#a89984",
                        overlay1 = "#928374",
                        overlay0 = "#595959",
                        surface2 = "#4d4d4d",
                        surface1 = "#404040",
                        surface0 = "#292929",
                        base = "#0d0e0e",
                        mantle = "#0a0b0b",
                        crust = "#060707",
                        -- base = "#070707",
                        -- mantle = "#0f0f0f",
                        -- crust = "#171717",
                    },
                },
                transparent_background = true,
                show_end_of_buffer = false,
                integration_default = false,
                integrations = {
                    barbecue = { dim_dirname = true, bold_basename = true, dim_context = false, alt_background = false },
                    cmp = true,
                    gitsigns = true,
                    hop = true,
                    illuminate = { enabled = true },
                    native_lsp = { enabled = true, inlay_hints = { background = true } },
                    neogit = true,
                    neotree = true,
                    semantic_tokens = true,
                    treesitter = true,
                    treesitter_context = true,
                    vimwiki = true,
                    which_key = true,
                },
                highlight_overrides = {
                    all = function(colors)
                        return {
                            -- UI
                            CmpItemMenu = { fg = colors.surface2 },
                            CursorLineNr = { fg = colors.text },
                            FloatBorder = { bg = colors.base, fg = colors.surface0 },
                            GitSignsChange = { fg = colors.peach },
                            LineNr = { fg = colors.overlay0 },
                            LspInfoBorder = { link = "FloatBorder" },
                            NeoTreeDirectoryIcon = { fg = colors.subtext1 },
                            NeoTreeDirectoryName = { fg = colors.subtext1 },
                            NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
                            NeoTreeGitConflict = { fg = colors.red },
                            NeoTreeGitDeleted = { fg = colors.red },
                            NeoTreeGitIgnored = { fg = colors.overlay0 },
                            NeoTreeGitModified = { fg = colors.peach },
                            NeoTreeGitStaged = { fg = colors.green },
                            NeoTreeGitUnstaged = { fg = colors.red },
                            NeoTreeGitUntracked = { fg = colors.green },
                            NeoTreeIndent = { fg = colors.surface1 },
                            NeoTreeNormal = { bg = colors.mantle },
                            NeoTreeNormalNC = { bg = colors.mantle },
                            NeoTreeRootName = { fg = colors.subtext1, style = { "bold" } },
                            NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
                            NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
                            NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
                            NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
                            NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
                            NormalFloat = { bg = colors.base },
                            Pmenu = { bg = colors.mantle, fg = "" },
                            PmenuSel = { bg = colors.surface0, fg = "" },
                            TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
                            TelescopePreviewNormal = { bg = colors.crust },
                            TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
                            TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
                            TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
                            TelescopePromptNormal = { bg = colors.surface0 },
                            TelescopePromptPrefix = { bg = colors.surface0 },
                            TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
                            TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
                            TelescopeResultsNormal = { bg = colors.mantle },
                            TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
                            TelescopeSelection = { bg = colors.surface0 },
                            VertSplit = { bg = colors.base, fg = colors.surface0 },
                            WhichKeyFloat = { bg = colors.mantle },
                            YankHighlight = { bg = colors.surface2 },
                            FidgetTask = { fg = colors.subtext2 },
                            FidgetTitle = { fg = colors.peach },
                            IblIndent = { fg = colors.surface0 },
                            IblScope = { fg = colors.overlay0 },

                            -- Traditional syntax
                            Boolean = { fg = colors.mauve },
                            Number = { fg = colors.mauve },
                            Float = { fg = colors.mauve },
                            PreProc = { fg = colors.mauve },
                            PreCondit = { fg = colors.mauve },
                            Include = { fg = colors.mauve },
                            Define = { fg = colors.mauve },
                            Conditional = { fg = colors.red },
                            Repeat = { fg = colors.red },
                            Keyword = { fg = colors.red },
                            Typedef = { fg = colors.red },
                            Exception = { fg = colors.red },
                            Statement = { fg = colors.red },
                            Error = { fg = colors.red },
                            StorageClass = { fg = colors.peach },
                            Tag = { fg = colors.peach },
                            Label = { fg = colors.peach },
                            Structure = { fg = colors.peach },
                            Operator = { fg = colors.peach },
                            Title = { fg = colors.peach },
                            Special = { fg = colors.yellow },
                            SpecialChar = { fg = colors.yellow },
                            Type = { fg = colors.yellow, style = { "bold" } },
                            Function = { fg = colors.green, style = { "bold" } },
                            Delimiter = { fg = colors.subtext2 },
                            Ignore = { fg = colors.subtext2 },
                            Macro = { fg = colors.teal },

                            -- Treesitter captures
                            ["@annotation"] = { fg = colors.mauve },
                            ["@attribute"] = { fg = colors.mauve },
                            ["@boolean"] = { fg = colors.mauve },
                            ["@character"] = { fg = colors.teal },
                            ["@character.special"] = { fg = colors.yellow },
                            ["@comment"] = { link = "Comment" },
                            ["@conceal"] = { fg = colors.overlay1 },
                            ["@conditional"] = { fg = colors.red },
                            ["@constant"] = { fg = colors.text },
                            ["@constant.builtin"] = { fg = colors.mauve },
                            ["@constant.macro"] = { fg = colors.mauve },
                            ["@constructor"] = { fg = colors.green },
                            ["@debug"] = { link = "Debug" },
                            ["@define"] = { fg = colors.mauve },
                            ["@error"] = { fg = colors.red },
                            ["@exception"] = { fg = colors.red },
                            ["@field"] = { fg = colors.blue },
                            ["@float"] = { fg = colors.mauve },
                            ["@function"] = { fg = colors.green },
                            ["@function.builtin"] = { fg = colors.green },
                            ["@function.call"] = { fg = colors.green },
                            ["@function.macro"] = { fg = colors.green },
                            ["@include"] = { fg = colors.red },
                            ["@keyword"] = { fg = colors.red },
                            ["@keyword.function"] = { fg = colors.red },
                            ["@keyword.operator"] = { fg = colors.peach },
                            ["@keyword.return"] = { fg = colors.red },
                            ["@label"] = { fg = colors.peach },
                            ["@math"] = { fg = colors.blue },
                            ["@method"] = { fg = colors.green },
                            ["@method.call"] = { fg = colors.green },
                            ["@namespace"] = { fg = colors.yellow },
                            ["@none"] = { fg = colors.text },
                            ["@number"] = { fg = colors.mauve },
                            ["@operator"] = { fg = colors.peach },
                            ["@parameter"] = { fg = colors.text },
                            ["@parameter.reference"] = { fg = colors.text },
                            ["@preproc"] = { fg = colors.mauve },
                            ["@property"] = { fg = colors.blue },
                            ["@punctuation.bracket"] = { fg = colors.text },
                            ["@punctuation.delimiter"] = { fg = colors.subtext2 },
                            ["@punctuation.special"] = { fg = colors.blue },
                            ["@repeat"] = { fg = colors.red },
                            ["@storageclass"] = { fg = colors.peach },
                            ["@storageclass.lifetime"] = { fg = colors.peach },
                            ["@strike"] = { fg = colors.subtext2 },
                            ["@string"] = { fg = colors.teal },
                            ["@string.escape"] = { fg = colors.green },
                            ["@string.regex"] = { fg = colors.green },
                            ["@string.special"] = { fg = colors.yellow },
                            ["@symbol"] = { fg = colors.text },
                            ["@tag"] = { fg = colors.peach },
                            ["@tag.attribute"] = { fg = colors.green },
                            ["@tag.delimiter"] = { fg = colors.green },
                            ["@text"] = { fg = colors.green },
                            ["@text.diff.add"] = { link = "diffAdded" },
                            ["@text.diff.delete"] = { link = "diffRemoved" },
                            ["@text.environment"] = { fg = colors.teal },
                            ["@text.environment.name"] = { fg = colors.yellow, style = { "bold" } },
                            ["@text.literal"] = { link = "String" },
                            ["@text.math"] = { fg = colors.blue },
                            ["@text.reference"] = { link = "Constant" },
                            ["@text.strike"] = { fg = colors.subtext2 },
                            ["@text.title"] = { fg = colors.peach },
                            ["@text.todo"] = { link = "Todo" },
                            ["@text.todo.checked"] = { fg = colors.green },
                            ["@text.todo.unchecked"] = { fg = colors.subtext2 },
                            ["@text.uri"] = { fg = colors.blue },
                            ["@todo"] = { link = "Todo" },
                            ["@type"] = { fg = colors.yellow, style = { "bold" } },
                            ["@type.builtin"] = { fg = colors.yellow, style = { "bold" } },
                            ["@type.definition"] = { fg = colors.yellow, style = { "bold" } },
                            ["@type.qualifier"] = { fg = colors.peach, style = { "bold" } },
                            ["@uri"] = { fg = colors.blue },
                            ["@variable"] = { fg = colors.text },
                            ["@variable.builtin"] = { fg = colors.mauve },

                            -- LSP semantic tokens (direct)
                            ["@lsp.type.class"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.comment"] = { link = "Comment" },
                            ["@lsp.type.decorator"] = { fg = colors.green },
                            ["@lsp.type.enum"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.enumMember"] = { fg = colors.blue },
                            ["@lsp.type.events"] = { fg = colors.peach },
                            ["@lsp.type.function"] = { fg = colors.green },
                            ["@lsp.type.interface"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.keyword"] = { fg = colors.red },
                            ["@lsp.type.macro"] = { fg = colors.mauve },
                            ["@lsp.type.method"] = { fg = colors.green },
                            ["@lsp.type.modifier"] = { fg = colors.peach, style = { "bold" } },
                            ["@lsp.type.namespace"] = { fg = colors.yellow },
                            ["@lsp.type.number"] = { fg = colors.mauve },
                            ["@lsp.type.operator"] = { fg = colors.peach },
                            ["@lsp.type.parameter"] = { fg = colors.text },
                            ["@lsp.type.property"] = { fg = colors.blue },
                            ["@lsp.type.regexp"] = { fg = colors.green },
                            ["@lsp.type.string"] = { fg = colors.teal },
                            ["@lsp.type.struct"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.type"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.typeParameter"] = { fg = colors.yellow, style = { "bold" } },
                            ["@lsp.type.variable"] = { fg = colors.text },
                        }
                    end,
                    latte = function(colors)
                        return {
                            IblIndent = { fg = colors.mantle },
                            IblScope = { fg = colors.surface1 },
                            LineNr = { fg = colors.surface1 },
                        }
                    end,
                },
            })
        end,
    },
    {
        "vague-theme/vague.nvim",
        lazy = true,
        priority = 1000,
        opts = {
            transparent = false,
            bold = true,
            italic = true,
        },
    },
    {
        "rose-pine/neovim",
        name = "rose-pine",
        lazy = true,
        priority = 1000,
        opts = {
            variant = "moon",
            extend_background_behind_borders = true,
        },
    },
    {
        "rebelot/kanagawa.nvim",
        lazy = true,
        priority = 1000,
        opts = {
            compile = true,
            theme = "dragon",
            background = {
                dark = "dragon",
            },
            overrides = function(colors)
                local theme = colors.theme
                return {
                    EndOfBuffer = {
                        fg = theme.ui.nontext,
                    },
                }
            end,
            colors = {
                theme = {
                    all = {
                        ui = {
                            bg_gutter = "none",
                        },
                    },
                },
            },
        },
    },
}
